Arman-ali-khan-786/CardUI

index.css

Fix delay icons social media

---

index.css
index.html

I have made the necessary changes

fix:#9 Add some font styles to Paragraph⭐

---

index.css

background color and other needed changes done. @Arman-ali-khan-786

changes in index.css

---

index.css
index.html

Fixes #36 
I chanded footer's size, font  and background color. Also changed images into icons.

Fix footer

---

darkModeBtn.css
index.html
index.js

Hi, I added the dark mode button and also the javascript required to change the theme of the page accordingly. 
Made sure that it is responsive and added CSS in a separate file so it is easier to manage in the future.

add dark mode button

---

index.css

Added a gradient scrollbar to beautify the index file as a contribution to open source

Added a gradient scrollbar

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE

Add hacktoberfest-accepted label to this.
Closes #49

made upto community standard

---

index.html

#64 
Solved an issue raised by maintainer regarding UI icons for the 8th UI card. Please have a look and accept the pr if found correct. Also kindly label the PR with hacktoberfest-accepted tag.
Thank you

Updated card number 8 UI icons

---

index.css

[fix] - fixed z-index of ui-7

---

darkModeBtn.css
index.css

header's color is changed and the shadow effect also is changed in light and dark themes both. I think now the header looking proper

Header Div colour changed

---

index.css

Fixed bug for UI-10 introduced due to PR #90 by IpsitaSenapati on lines 1035 and 1217 of the index.css file.

Fixed bug for UI-10 introduced due to PR #90 by IpsitaSenapati

---

index.css
index.html

feat: added card ui 13

---

index.css
index.html

Hi @Arman-ali-khan-786, I added the animation to the footer icons and left the footer design as it was earlier just like you told me to do. please review the changes

add social link animation

---

index.css
index.html

hey @Arman-ali-khan-786 , did the changes. please review

updated the social animations to apply only to main page footer

---

index.html

Fixed UI of first 6 buttons of click here for code

---

.vscode/settings.json

https://user-images.githubusercontent.com/106283743/231432543-88c0e880-2500-49db-a2d1-3e051fabc72f.mp4

I have added the source code button instead of "Click here for the code" text. As per issue #129

---

darkModeBtn.css
index.css

responsiveness issues are solved please check it out

solved responsive issues

---

index.css
index.html

previous
after changes
loading of socials is enhanced , footer size is reduced .

Made changes to footer

---

index.css

changed "source code" btn color to #fff
so its visible in dark mode as well

fixed #146

---

index.css
index.html

 UI card 25
